language: node_js
node_js: '6'
install:
   - npm install yarn -g
   - yarn install
   - npm install # fix
script:
    - npm test
    - npm run build
    - npm run build:prod
cache:
  directories:
     - $HOME/.npm
     - $HOME/.yarn-cache
